### ISSUE TITLE
Mapping of A, B, C orientation angles to rotation matrices/ Quaternions

### ISSUE THREAD

**Issue by prajval10** [cjlh/kuka-rsi-ros-interface#1]
As far as our understanding goes, A,B,C angles map to `base_R_ee` which is end-effector mapped in base frame. However according to this equation: https://github.com/cjlh/kuka-rsi-ros-interface/blob/5f4671209c6d0f4d9f64dae607c8918904f79acc/catkin_ws/src/kuka_rsi_ros_interface/kuka_rsi_ros_interface_core/src/KukaRsiRosInterface.cpp#L248

It seems that reading the measurement values from RSI transposes the equivalent matrix, i.e., it becomes `ee_R_base`. This holds the above multiplication true (using Rot matrices instead of quaternions for simplicity)
```
Rot_new = goal_R_base * (current_R_base)^T
```
This was verified to be working in our implementation as well, we use rotation matrices instead of quaternions. This mapping is indeed a bit strange and opposite to the normal mapping which is position and orientation of end-effector expressed in base/ world frame.

**Comment by cjlh** [comment]
Hi Prajval,

It's great to see you're finding this package useful!

Would you mind explaining a bit more about the issue you're having here? I'm not sure I'm understanding it correctly. As I understand it, multiplying by the transpose of a rotation matrix as you describe is equivalent to multiplying by the inverse quaternion, so I believe the equation you've given is equivalent to the quaternion operation in the code.

It may also be worth noting that I no longer have access to a KUKA robot set-up so will not be able to test any changes to the code -- I therefore won't be updating this package for the foreseeable future. You're more than welcome to fork the repository if you think it could be improved, however. :)

**Comment by prajval10** [comment]
Hi Caleb,

To keep it simple, could you please explain how `q_goal` and `q_current` are expressed with respect to the base frame in the equation:
```
tf::Quaternion q_new = q_goal * q_curr.inverse(); 
```
Is `q_goal = base_R_ee` (end-effector expressed in base frame) or `ee_R_base` (the corresponding transpose)?

Thanks!

**Comment by cjlh** [comment]
Hi Prajval,

Apologies for the delay in responding to you, I had intended to look into this earlier but it slipped my mind. I'll try to explain what's going on in the code to clear this up:

The quaternion `q_goal` is created using the YPR values of the final goal pose that the robot is desired to move towards -- this is the position of the robot's end-effector in the robot base frame, the same frame as used by RobotSensorInterface and the same frame as `q_curr`. The goal pose is that which is given to the `KukaRsiRosInterface::moveToPosition` method.

The pose quaternion `q_curr` is derived from the XML response of the controller in the method `KukaRsiRosInterface::getPositionDataFromResponse`. The A, B, C angles (along with X, Y, Z position) are taken from the `RIst` element of this XML data (the "Cartesian actual position" of the end effector, as described in the RSI documentation).

The quaternion `q_new` is then simply the rotation necessary to move from the current position into the goal position. In the following line of `KukaRsiRosInterface.cpp` you can see that the angle of this rotation is then taken for use in calculating the adjustment pose, using `q_new.getAngle()`.

The process for taking this angle is explained nicely in [this StackExchange answer](https://math.stackexchange.com/a/167828).

If this sounds confusing or if you're still not clear, let me know which bit needs clearing up and I'll try to get back to you as soon as I can.

Cheers!

**Comment by prajval10** [comment]
Thanks!

**Comment by cjlh** [comment]
No problem, glad I could help!
